//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace DeMonic
{
	using System.Xml.Serialization;


	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	[XmlRootAttribute("subsonic-response", Namespace = "http://subsonic.org/restapi", IsNullable = false)]
	public partial class SubsonicResponse
	{

		private object itemField;

		private ItemChoiceType itemElementNameField;

		private ResponseStatus statusField;

		private string versionField;

		[XmlElementAttribute("album", typeof(AlbumWithSongsID3))]
		[XmlElementAttribute("albumInfo", typeof(AlbumInfo))]
		[XmlElementAttribute("albumList", typeof(AlbumList))]
		[XmlElementAttribute("albumList2", typeof(AlbumList2))]
		[XmlElementAttribute("artist", typeof(ArtistWithAlbumsID3))]
		[XmlElementAttribute("artistInfo", typeof(ArtistInfo))]
		[XmlElementAttribute("artistInfo2", typeof(ArtistInfo2))]
		[XmlElementAttribute("artists", typeof(ArtistsID3))]
		[XmlElementAttribute("bookmarks", typeof(Bookmarks))]
		[XmlElementAttribute("chatMessages", typeof(ChatMessages))]
		[XmlElementAttribute("directory", typeof(Directory))]
		[XmlElementAttribute("error", typeof(Error))]
		[XmlElementAttribute("genres", typeof(Genres))]
		[XmlElementAttribute("indexes", typeof(Indexes))]
		[XmlElementAttribute("internetRadioStations", typeof(InternetRadioStations))]
		[XmlElementAttribute("jukeboxPlaylist", typeof(JukeboxPlaylist))]
		[XmlElementAttribute("jukeboxStatus", typeof(JukeboxStatus))]
		[XmlElementAttribute("license", typeof(License))]
		[XmlElementAttribute("lyrics", typeof(Lyrics))]
		[XmlElementAttribute("musicFolders", typeof(MusicFolders))]
		[XmlElementAttribute("newestPodcasts", typeof(NewestPodcasts))]
		[XmlElementAttribute("nowPlaying", typeof(NowPlaying))]
		[XmlElementAttribute("playQueue", typeof(PlayQueue))]
		[XmlElementAttribute("playlist", typeof(PlaylistWithSongs))]
		[XmlElementAttribute("playlists", typeof(Playlists))]
		[XmlElementAttribute("podcasts", typeof(Podcasts))]
		[XmlElementAttribute("randomSongs", typeof(Songs))]
		[XmlElementAttribute("scanStatus", typeof(ScanStatus))]
		[XmlElementAttribute("searchResult", typeof(SearchResult))]
		[XmlElementAttribute("searchResult2", typeof(SearchResult2))]
		[XmlElementAttribute("searchResult3", typeof(SearchResult3))]
		[XmlElementAttribute("shares", typeof(Shares))]
		[XmlElementAttribute("similarSongs", typeof(SimilarSongs))]
		[XmlElementAttribute("similarSongs2", typeof(SimilarSongs2))]
		[XmlElementAttribute("song", typeof(Child))]
		[XmlElementAttribute("songsByGenre", typeof(Songs))]
		[XmlElementAttribute("starred", typeof(Starred))]
		[XmlElementAttribute("starred2", typeof(Starred2))]
		[XmlElementAttribute("topSongs", typeof(TopSongs))]
		[XmlElementAttribute("user", typeof(User))]
		[XmlElementAttribute("users", typeof(Users))]
		[XmlElementAttribute("videoInfo", typeof(VideoInfo))]
		[XmlElementAttribute("videos", typeof(Videos))]
		[XmlChoiceIdentifierAttribute("ItemElementName")]
		public object Item;

		[XmlIgnoreAttribute()]
		public ItemChoiceType ItemElementName;

		[XmlAttributeAttribute()]
		public ResponseStatus status;

		[XmlAttributeAttribute()]
		public string version;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class AlbumWithSongsID3 : AlbumID3
	{

		private Child[] songField;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[XmlIncludeAttribute(typeof(PodcastEpisode))]
	[XmlIncludeAttribute(typeof(NowPlayingEntry))]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Child
	{
		private string idField;
		private string parentField;
		private bool isDirField;
		private string titleField;
		private string albumField;
		private string artistField;
		private int trackField;
		private bool trackFieldSpecified;
		private int yearField;
		private bool yearFieldSpecified;
		private string genreField;
		private string coverArtField;
		private long sizeField;
		private bool sizeFieldSpecified;
		private string contentTypeField;
		private string suffixField;
		private string transcodedContentTypeField;
		private string transcodedSuffixField;
		private int durationField;
		private bool durationFieldSpecified;
		private int bitRateField;
		private bool bitRateFieldSpecified;
		private string pathField;
		private bool isVideoField;
		private bool isVideoFieldSpecified;
		private int userRatingField;
		private bool userRatingFieldSpecified;
		private double averageRatingField;
		private bool averageRatingFieldSpecified;
		private long playCountField;
		private bool playCountFieldSpecified;
		private int discNumberField;
		private bool discNumberFieldSpecified;
		private System.DateTime createdField;
		private bool createdFieldSpecified;
		private System.DateTime starredField;
		private bool starredFieldSpecified;
		private string albumIdField;
		private string artistIdField;
		private MediaType typeField;
		private bool typeFieldSpecified;
		private long bookmarkPositionField;
		private bool bookmarkPositionFieldSpecified;
		private int originalWidthField;
		private bool originalWidthFieldSpecified;
		private int originalHeightField;
		private bool originalHeightFieldSpecified;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string parent;

		[XmlAttributeAttribute()]
		public bool isDir;

		[XmlAttributeAttribute()]
		public string title;

		[XmlAttributeAttribute()]
		public string album;

		[XmlAttributeAttribute()]
		public string artist;

		[XmlAttributeAttribute()]
		public int track;

		[XmlIgnoreAttribute()]
		public bool trackSpecified;

		[XmlAttributeAttribute()]
		public int year;

		[XmlIgnoreAttribute()]
		public bool yearSpecified;

		[XmlAttributeAttribute()]
		public string genre;

		[XmlAttributeAttribute()]
		public string coverArt;

		[XmlAttributeAttribute()]
		public long size;

		[XmlIgnoreAttribute()]
		public bool sizeSpecified;

		[XmlAttributeAttribute()]
		public string contentType;

		[XmlAttributeAttribute()]
		public string suffix;

		[XmlAttributeAttribute()]
		public string transcodedContentType;

		[XmlAttributeAttribute()]
		public string transcodedSuffix;

		[XmlAttributeAttribute()]
		public int duration;

		[XmlIgnoreAttribute()]
		public bool durationSpecified;

		[XmlAttributeAttribute()]
		public int bitRate;

		[XmlIgnoreAttribute()]
		public bool bitRateSpecified;

		[XmlAttributeAttribute()]
		public string path;

		[XmlAttributeAttribute()]
		public bool isVideo;

		[XmlIgnoreAttribute()]
		public bool isVideoSpecified;

		[XmlAttributeAttribute()]
		public int userRating;

		[XmlIgnoreAttribute()]
		public bool userRatingSpecified;

		[XmlAttributeAttribute()]
		public double averageRating;

		[XmlIgnoreAttribute()]
		public bool averageRatingSpecified;

		[XmlAttributeAttribute()]
		public long playCount;

		[XmlIgnoreAttribute()]
		public bool playCountSpecified;

		[XmlAttributeAttribute()]
		public int discNumber;

		[XmlIgnoreAttribute()]
		public bool discNumberSpecified;

		[XmlAttributeAttribute()]
		public System.DateTime created;

		[XmlIgnoreAttribute()]
		public bool createdSpecified;

		[XmlAttributeAttribute()]
		public System.DateTime starred;

		[XmlIgnoreAttribute()]
		public bool starredSpecified;

		[XmlAttributeAttribute()]
		public string albumId;

		[XmlAttributeAttribute()]
		public string artistId;

		[XmlAttributeAttribute()]
		public MediaType type;

		[XmlIgnoreAttribute()]
		public bool typeSpecified;

		[XmlAttributeAttribute()]
		public long bookmarkPosition;

		[XmlIgnoreAttribute()]
		public bool bookmarkPositionSpecified;

		[XmlAttributeAttribute()]
		public int originalWidth;

		[XmlIgnoreAttribute()]
		public bool originalWidthSpecified;

		[XmlAttributeAttribute()]
		public int originalHeight;

		[XmlIgnoreAttribute()]
		public bool originalHeightSpecified;
	}

	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public enum MediaType
	{

		music,

		podcast,

		audiobook,

		video,
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Error
	{

		private int codeField;

		private string messageField;

		[XmlAttributeAttribute()]
		public int code;

		[XmlAttributeAttribute()]
		public string message;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ScanStatus
	{

		private bool scanningField;

		private long countField;

		private bool countFieldSpecified;

		[XmlAttributeAttribute()]
		public bool scanning;

		[XmlAttributeAttribute()]
		public long count;

		[XmlIgnoreAttribute()]
		public bool countSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class TopSongs
	{

		private Child[] songField;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class SimilarSongs2
	{

		private Child[] songField;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class SimilarSongs
	{

		private Child[] songField;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[XmlIncludeAttribute(typeof(ArtistInfo2))]
	[XmlIncludeAttribute(typeof(ArtistInfo))]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ArtistInfoBase
	{
		private string biographyField;
		private string musicBrainzIdField;
		private string lastFmUrlField;
		private string smallImageUrlField;
		private string mediumImageUrlField;
		private string largeImageUrlField;
		public string biography;
		public string musicBrainzId;
		public string lastFmUrl;
		public string smallImageUrl;
		public string mediumImageUrl;
		public string largeImageUrl;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ArtistInfo2 : ArtistInfoBase
	{

		private ArtistID3[] similarArtistField;

		[XmlElementAttribute("similarArtist")]
		public ArtistID3[] similarArtist;
	}

	[XmlIncludeAttribute(typeof(ArtistWithAlbumsID3))]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ArtistID3
	{
		private string idField;
		private string nameField;
		private string coverArtField;
		private int albumCountField;
		private System.DateTime starredField;
		private bool starredFieldSpecified;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public string coverArt;

		[XmlAttributeAttribute()]
		public int albumCount;

		[XmlAttributeAttribute()]
		public System.DateTime starred;

		[XmlIgnoreAttribute()]
		public bool starredSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ArtistWithAlbumsID3 : ArtistID3
	{

		private AlbumID3[] albumField;

		[XmlElementAttribute("album")]
		public AlbumID3[] album;
	}

	[XmlIncludeAttribute(typeof(AlbumWithSongsID3))]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class AlbumID3
	{
		private string idField;
		private string nameField;
		private string artistField;
		private string artistIdField;
		private string coverArtField;
		private int songCountField;
		private int durationField;
		private long playCountField;
		private bool playCountFieldSpecified;
		private System.DateTime createdField;
		private System.DateTime starredField;
		private bool starredFieldSpecified;
		private int yearField;
		private bool yearFieldSpecified;
		private string genreField;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public string artist;

		[XmlAttributeAttribute()]
		public string artistId;

		[XmlAttributeAttribute()]
		public string coverArt;

		[XmlAttributeAttribute()]
		public int songCount;

		[XmlAttributeAttribute()]
		public int duration;

		[XmlAttributeAttribute()]
		public long playCount;

		[XmlIgnoreAttribute()]
		public bool playCountSpecified;

		[XmlAttributeAttribute()]
		public System.DateTime created;

		[XmlAttributeAttribute()]
		public System.DateTime starred;

		[XmlIgnoreAttribute()]
		public bool starredSpecified;

		[XmlAttributeAttribute()]
		public int year;

		[XmlIgnoreAttribute()]
		public bool yearSpecified;

		[XmlAttributeAttribute()]
		public string genre;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ArtistInfo : ArtistInfoBase
	{

		private Artist[] similarArtistField;

		[XmlElementAttribute("similarArtist")]
		public Artist[] similarArtist;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Artist
	{
		private string idField;
		private string nameField;
		private System.DateTime starredField;
		private bool starredFieldSpecified;
		private int userRatingField;
		private bool userRatingFieldSpecified;
		private double averageRatingField;
		private bool averageRatingFieldSpecified;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public System.DateTime starred;

		[XmlIgnoreAttribute()]
		public bool starredSpecified;

		[XmlAttributeAttribute()]
		public int userRating;

		[XmlIgnoreAttribute()]
		public bool userRatingSpecified;

		[XmlAttributeAttribute()]
		public double averageRating;

		[XmlIgnoreAttribute()]
		public bool averageRatingSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class AlbumInfo
	{
		private string notesField;
		private string musicBrainzIdField;
		private string lastFmUrlField;
		private string smallImageUrlField;
		private string mediumImageUrlField;
		private string largeImageUrlField;
		public string notes;
		public string musicBrainzId;
		public string lastFmUrl;
		public string smallImageUrl;
		public string mediumImageUrl;
		public string largeImageUrl;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Starred2
	{
		private ArtistID3[] artistField;
		private AlbumID3[] albumField;
		private Child[] songField;

		[XmlElementAttribute("artist")]
		public ArtistID3[] artist;

		[XmlElementAttribute("album")]
		public AlbumID3[] album;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Starred
	{
		private Artist[] artistField;
		private Child[] albumField;
		private Child[] songField;

		[XmlElementAttribute("artist")]
		public Artist[] artist;

		[XmlElementAttribute("album")]
		public Child[] album;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Shares
	{
		private Share[] shareField;

		[XmlElementAttribute("share")]
		public Share[] share;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Share
	{
		private Child[] entryField;
		private string idField;
		private string urlField;
		private string descriptionField;
		private string usernameField;
		private System.DateTime createdField;
		private System.DateTime expiresField;
		private bool expiresFieldSpecified;
		private System.DateTime lastVisitedField;
		private bool lastVisitedFieldSpecified;
		private int visitCountField;

		[XmlElementAttribute("entry")]
		public Child[] entry;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string url;

		[XmlAttributeAttribute()]
		public string description;

		[XmlAttributeAttribute()]
		public string username;

		[XmlAttributeAttribute()]
		public System.DateTime created;

		[XmlAttributeAttribute()]
		public System.DateTime expires;

		[XmlIgnoreAttribute()]
		public bool expiresSpecified;

		[XmlAttributeAttribute()]
		public System.DateTime lastVisited;

		[XmlIgnoreAttribute()]
		public bool lastVisitedSpecified;

		[XmlAttributeAttribute()]
		public int visitCount;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class PlayQueue
	{
		private Child[] entryField;
		private int currentField;
		private bool currentFieldSpecified;
		private long positionField;
		private bool positionFieldSpecified;
		private string usernameField;
		private System.DateTime changedField;
		private string changedByField;

		[XmlElementAttribute("entry")]
		public Child[] entry;

		[XmlAttributeAttribute()]
		public int current;

		[XmlIgnoreAttribute()]
		public bool currentSpecified;

		[XmlAttributeAttribute()]
		public long position;

		[XmlIgnoreAttribute()]
		public bool positionSpecified;

		[XmlAttributeAttribute()]
		public string username;

		[XmlAttributeAttribute()]
		public System.DateTime changed;

		[XmlAttributeAttribute()]
		public string changedBy;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Bookmarks
	{
		private Bookmark[] bookmarkField;

		[XmlElementAttribute("bookmark")]
		public Bookmark[] bookmark;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Bookmark
	{
		private Child entryField;
		private long positionField;
		private string usernameField;
		private string commentField;
		private System.DateTime createdField;
		private System.DateTime changedField;
		public Child entry;

		[XmlAttributeAttribute()]
		public long position;

		[XmlAttributeAttribute()]
		public string username;

		[XmlAttributeAttribute()]
		public string comment;

		[XmlAttributeAttribute()]
		public System.DateTime created;

		[XmlAttributeAttribute()]
		public System.DateTime changed;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class InternetRadioStations
	{

		private InternetRadioStation[] internetRadioStationField;

		[XmlElementAttribute("internetRadioStation")]
		public InternetRadioStation[] internetRadioStation;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class InternetRadioStation
	{
		private string idField;
		private string nameField;
		private string streamUrlField;
		private string homePageUrlField;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public string streamUrl;

		[XmlAttributeAttribute()]
		public string homePageUrl;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class NewestPodcasts
	{
		private PodcastEpisode[] episodeField;

		[XmlElementAttribute("episode")]
		public PodcastEpisode[] episode;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class PodcastEpisode : Child
	{
		private string streamIdField;
		private string channelIdField;
		private string descriptionField;
		private PodcastStatus statusField;
		private System.DateTime publishDateField;
		private bool publishDateFieldSpecified;

		[XmlAttributeAttribute()]
		public string streamId;

		[XmlAttributeAttribute()]
		public string channelId;

		[XmlAttributeAttribute()]
		public string description;

		[XmlAttributeAttribute()]
		public PodcastStatus status;

		[XmlAttributeAttribute()]
		public System.DateTime publishDate;

		[XmlIgnoreAttribute()]
		public bool publishDateSpecified;
	}

	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public enum PodcastStatus
	{
		@new,
		downloading,
		completed,
		error,
		deleted,
		skipped,
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Podcasts
	{

		private PodcastChannel[] channelField;

		[XmlElementAttribute("channel")]
		public PodcastChannel[] channel;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class PodcastChannel
	{
		private PodcastEpisode[] episodeField;
		private string idField;
		private string urlField;
		private string titleField;
		private string descriptionField;
		private string coverArtField;
		private string originalImageUrlField;
		private PodcastStatus statusField;
		private string errorMessageField;

		[XmlElementAttribute("episode")]
		public PodcastEpisode[] episode;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string url;

		[XmlAttributeAttribute()]
		public string title;

		[XmlAttributeAttribute()]
		public string description;

		[XmlAttributeAttribute()]
		public string coverArt;

		[XmlAttributeAttribute()]
		public string originalImageUrl;

		[XmlAttributeAttribute()]
		public PodcastStatus status;

		[XmlAttributeAttribute()]
		public string errorMessage;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Lyrics
	{
		private string artistField;
		private string titleField;
		private string[] textField;

		[XmlAttributeAttribute()]
		public string artist;

		[XmlAttributeAttribute()]
		public string title;

		[XmlTextAttribute()]
		public string[] Text;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Songs
	{
		private Child[] songField;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class AlbumList2
	{
		private AlbumID3[] albumField;

		[XmlElementAttribute("album")]
		public AlbumID3[] album;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class AlbumList
	{
		private Child[] albumField;

		[XmlElementAttribute("album")]
		public Child[] album;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ChatMessages
	{
		private ChatMessage[] chatMessageField;

		[XmlElementAttribute("chatMessage")]
		public ChatMessage[] chatMessage;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ChatMessage
	{
		private string usernameField;
		private long timeField;
		private string messageField;

		[XmlAttributeAttribute()]
		public string username;

		[XmlAttributeAttribute()]
		public long time;

		[XmlAttributeAttribute()]
		public string message;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Users
	{
		private User[] userField;

		[XmlElementAttribute("user")]
		public User[] user;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class User
	{
		private int[] folderField;
		private string usernameField;
		private string emailField;
		private bool scrobblingEnabledField;
		private int maxBitRateField;
		private bool maxBitRateFieldSpecified;
		private bool adminRoleField;
		private bool settingsRoleField;
		private bool downloadRoleField;
		private bool uploadRoleField;
		private bool playlistRoleField;
		private bool coverArtRoleField;
		private bool commentRoleField;
		private bool podcastRoleField;
		private bool streamRoleField;
		private bool jukeboxRoleField;
		private bool shareRoleField;
		private bool videoConversionRoleField;
		private System.DateTime avatarLastChangedField;
		private bool avatarLastChangedFieldSpecified;

		[XmlElementAttribute("folder")]
		public int[] folder;

		[XmlAttributeAttribute()]
		public string username;

		[XmlAttributeAttribute()]
		public string email;

		[XmlAttributeAttribute()]
		public bool scrobblingEnabled;

		[XmlAttributeAttribute()]
		public int maxBitRate;

		[XmlIgnoreAttribute()]
		public bool maxBitRateSpecified;

		[XmlAttributeAttribute()]
		public bool adminRole;

		[XmlAttributeAttribute()]
		public bool settingsRole;

		[XmlAttributeAttribute()]
		public bool downloadRole;

		[XmlAttributeAttribute()]
		public bool uploadRole;

		[XmlAttributeAttribute()]
		public bool playlistRole;

		[XmlAttributeAttribute()]
		public bool coverArtRole;

		[XmlAttributeAttribute()]
		public bool commentRole;

		[XmlAttributeAttribute()]
		public bool podcastRole;

		[XmlAttributeAttribute()]
		public bool streamRole;

		[XmlAttributeAttribute()]
		public bool jukeboxRole;

		[XmlAttributeAttribute()]
		public bool shareRole;

		[XmlAttributeAttribute()]
		public bool videoConversionRole;

		[XmlAttributeAttribute()]
		public System.DateTime avatarLastChanged;

		[XmlIgnoreAttribute()]
		public bool avatarLastChangedSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class License
	{
		private bool validField;
		private string emailField;
		private System.DateTime licenseExpiresField;
		private bool licenseExpiresFieldSpecified;
		private System.DateTime trialExpiresField;
		private bool trialExpiresFieldSpecified;

		[XmlAttributeAttribute()]
		public bool valid;

		[XmlAttributeAttribute()]
		public string email;

		[XmlAttributeAttribute()]
		public System.DateTime licenseExpires;

		[XmlIgnoreAttribute()]
		public bool licenseExpiresSpecified;

		[XmlAttributeAttribute()]
		public System.DateTime trialExpires;

		[XmlIgnoreAttribute()]
		public bool trialExpiresSpecified;
	}

	[XmlIncludeAttribute(typeof(JukeboxPlaylist))]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class JukeboxStatus
	{
		private int currentIndexField;
		private bool playingField;
		private float gainField;
		private int positionField;
		private bool positionFieldSpecified;

		[XmlAttributeAttribute()]
		public int currentIndex;

		[XmlAttributeAttribute()]
		public bool playing;

		[XmlAttributeAttribute()]
		public float gain;

		[XmlAttributeAttribute()]
		public int position;

		[XmlIgnoreAttribute()]
		public bool positionSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class JukeboxPlaylist : JukeboxStatus
	{
		private Child[] entryField;

		[XmlElementAttribute("entry")]
		public Child[] entry;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Playlists
	{
		private Playlist[] playlistField;

		[XmlElementAttribute("playlist")]
		public Playlist[] playlist;
	}

	[XmlIncludeAttribute(typeof(PlaylistWithSongs))]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Playlist
	{
		private string[] allowedUserField;
		private string idField;
		private string nameField;
		private string commentField;
		private string ownerField;
		private bool publicField;
		private bool publicFieldSpecified;
		private int songCountField;
		private int durationField;
		private System.DateTime createdField;
		private System.DateTime changedField;
		private string coverArtField;

		[XmlElementAttribute("allowedUser")]
		public string[] allowedUser;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public string comment;

		[XmlAttributeAttribute()]
		public string owner;

		[XmlAttributeAttribute()]
		public bool @public;

		[XmlIgnoreAttribute()]
		public bool publicSpecified;

		[XmlAttributeAttribute()]
		public int songCount;

		[XmlAttributeAttribute()]
		public int duration;

		[XmlAttributeAttribute()]
		public System.DateTime created;

		[XmlAttributeAttribute()]
		public System.DateTime changed;

		[XmlAttributeAttribute()]
		public string coverArt;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class PlaylistWithSongs : Playlist
	{
		private Child[] entryField;

		[XmlElementAttribute("entry")]
		public Child[] entry;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class SearchResult3
	{
		private ArtistID3[] artistField;
		private AlbumID3[] albumField;
		private Child[] songField;

		[XmlElementAttribute("artist")]
		public ArtistID3[] artist;

		[XmlElementAttribute("album")]
		public AlbumID3[] album;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class SearchResult2
	{
		private Artist[] artistField;
		private Child[] albumField;
		private Child[] songField;

		[XmlElementAttribute("artist")]
		public Artist[] artist;

		[XmlElementAttribute("album")]
		public Child[] album;

		[XmlElementAttribute("song")]
		public Child[] song;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class SearchResult
	{
		private Child[] matchField;
		private int offsetField;
		private int totalHitsField;

		[XmlElementAttribute("match")]
		public Child[] match;

		[XmlAttributeAttribute()]
		public int offset;

		[XmlAttributeAttribute()]
		public int totalHits;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class NowPlaying
	{
		private NowPlayingEntry[] entryField;

		[XmlElementAttribute("entry")]
		public NowPlayingEntry[] entry;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class NowPlayingEntry : Child
	{
		private string usernameField;
		private int minutesAgoField;
		private int playerIdField;
		private string playerNameField;

		[XmlAttributeAttribute()]
		public string username;

		[XmlAttributeAttribute()]
		public int minutesAgo;

		[XmlAttributeAttribute()]
		public int playerId;

		[XmlAttributeAttribute()]
		public string playerName;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class VideoConversion
	{
		private string idField;
		private int bitRateField;
		private bool bitRateFieldSpecified;
		private int audioTrackIdField;
		private bool audioTrackIdFieldSpecified;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public int bitRate;

		[XmlIgnoreAttribute()]
		public bool bitRateSpecified;

		[XmlAttributeAttribute()]
		public int audioTrackId;

		[XmlIgnoreAttribute()]
		public bool audioTrackIdSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class AudioTrack
	{
		private string idField;
		private string nameField;
		private string languageCodeField;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public string languageCode;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Captions
	{
		private string idField;
		private string nameField;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string name;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class VideoInfo
	{
		private Captions[] captionsField;
		private AudioTrack[] audioTrackField;
		private VideoConversion[] conversionField;
		private string idField;

		[XmlElementAttribute("captions")]
		public Captions[] captions;

		[XmlElementAttribute("audioTrack")]
		public AudioTrack[] audioTrack;

		[XmlElementAttribute("conversion")]
		public VideoConversion[] conversion;

		[XmlAttributeAttribute()]
		public string id;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Videos
	{
		private Child[] videoField;

		[XmlElementAttribute("video")]
		public Child[] video;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class IndexID3
	{
		private ArtistID3[] artistField;
		private string nameField;

		[XmlElementAttribute("artist")]
		public ArtistID3[] artist;

		[XmlAttributeAttribute()]
		public string name;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class ArtistsID3
	{
		private IndexID3[] indexField;
		private string ignoredArticlesField;

		[XmlElementAttribute("index")]
		public IndexID3[] index;

		[XmlAttributeAttribute()]
		public string ignoredArticles;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Genres
	{
		private Genre[] genreField;

		[XmlElementAttribute("genre")]
		public Genre[] genre;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Genre
	{
		private int songCountField;
		private int albumCountField;
		private string[] textField;

		[XmlAttributeAttribute()]
		public int songCount;

		[XmlAttributeAttribute()]
		public int albumCount;

		[XmlTextAttribute()]
		public string[] Text;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Directory
	{
		private Child[] childField;
		private string idField;
		private string parentField;
		private string nameField;
		private System.DateTime starredField;
		private bool starredFieldSpecified;
		private int userRatingField;
		private bool userRatingFieldSpecified;
		private double averageRatingField;
		private bool averageRatingFieldSpecified;
		private long playCountField;
		private bool playCountFieldSpecified;

		[XmlElementAttribute("child")]
		public Child[] child;

		[XmlAttributeAttribute()]
		public string id;

		[XmlAttributeAttribute()]
		public string parent;

		[XmlAttributeAttribute()]
		public string name;

		[XmlAttributeAttribute()]
		public System.DateTime starred;

		[XmlIgnoreAttribute()]
		public bool starredSpecified;

		[XmlAttributeAttribute()]
		public int userRating;

		[XmlIgnoreAttribute()]
		public bool userRatingSpecified;

		[XmlAttributeAttribute()]
		public double averageRating;

		[XmlIgnoreAttribute()]
		public bool averageRatingSpecified;

		[XmlAttributeAttribute()]
		public long playCount;

		[XmlIgnoreAttribute()]
		public bool playCountSpecified;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Index
	{
		private Artist[] artistField;
		private string nameField;

		[XmlElementAttribute("artist")]
		public Artist[] artist;

		[XmlAttributeAttribute()]
		public string name;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class Indexes
	{
		private Artist[] shortcutField;
		private Index[] indexField;
		private Child[] childField;
		private long lastModifiedField;
		private string ignoredArticlesField;

		[XmlElementAttribute("shortcut")]
		public Artist[] shortcut;

		[XmlElementAttribute("index")]
		public Index[] index;

		[XmlElementAttribute("child")]
		public Child[] child;

		[XmlAttributeAttribute()]
		public long lastModified;

		[XmlAttributeAttribute()]
		public string ignoredArticles;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class MusicFolders
	{
		private MusicFolder[] musicFolderField;

		[XmlElementAttribute("musicFolder")]
		public MusicFolder[] musicFolder;
	}

	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public partial class MusicFolder
	{
		private int idField;
		private string nameField;

		[XmlAttributeAttribute()]
		public int id;

		[XmlAttributeAttribute()]
		public string name;
	}

	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi", IncludeInSchema = false)]
	public enum ItemChoiceType
	{
		album,
		albumInfo,
		albumList,
		albumList2,
		artist,
		artistInfo,
		artistInfo2,
		artists,
		bookmarks,
		chatMessages,
		directory,
		error,
		genres,
		indexes,
		internetRadioStations,
		jukeboxPlaylist,
		jukeboxStatus,
		license,
		lyrics,
		musicFolders,
		newestPodcasts,
		nowPlaying,
		playQueue,
		playlist,
		playlists,
		podcasts,
		randomSongs,
		scanStatus,
		searchResult,
		searchResult2,
		searchResult3,
		shares,
		similarSongs,
		similarSongs2,
		song,
		songsByGenre,
		starred,
		starred2,
		topSongs,
		user,
		users,
		videoInfo,
		videos,
	}

	[System.SerializableAttribute()]
	[XmlTypeAttribute(Namespace = "http://subsonic.org/restapi")]
	public enum ResponseStatus
	{
		ok,
		failed,
	}
}
